bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 5
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 2e-5
learning_rate_te = 2e-5
logging_dir = "C:/Users/Sanjay_PC/Downloads/reg_data/log"
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 1500
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0.3
noise_offset_type = "Original"
optimizer_type = "Adafactor"
output_dir = "C:/Users/Sanjay_PC/Downloads/reg_data/model"
output_name = "fitme"
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
prior_loss_weight = 1
reg_data_dir = "C:/Users/Sanjay_PC/Downloads/reg_data/reg"
resolution = "512,512"
sample_prompts = "C:/Users/Sanjay_PC/Downloads/reg_data/model\\prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "ckpt"
save_precision = "fp16"
train_batch_size = 3
train_data_dir = "C:/Users/Sanjay_PC/Downloads/reg_data"
xformers = true
